// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvZRZCODoT05Woxs7Zp8PrUvKXDYbeZQ',
    appId: '1:223244759279:web:9518ecf549f0be9e69eb1a',
    messagingSenderId: '223244759279',
    projectId: 'gemdoc-22afc',
    authDomain: 'gemdoc-22afc.firebaseapp.com',
    storageBucket: 'gemdoc-22afc.firebasestorage.app',
    measurementId: 'G-4X9GBSY39V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FHivNMjLpmsvj6PpiGc-zOEkDtwznmY',
    appId: '1:223244759279:android:b60e0e40b80bb80e69eb1a',
    messagingSenderId: '223244759279',
    projectId: 'gemdoc-22afc',
    storageBucket: 'gemdoc-22afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdKyH1PNcmjguD9R7ZRKddpPNApEUAKs',
    appId: '1:223244759279:ios:6476c85dd37abac869eb1a',
    messagingSenderId: '223244759279',
    projectId: 'gemdoc-22afc',
    storageBucket: 'gemdoc-22afc.firebasestorage.app',
    iosBundleId: 'com.example.gemdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdKyH1PNcmjguD9R7ZRKddpPNApEUAKs',
    appId: '1:223244759279:ios:6476c85dd37abac869eb1a',
    messagingSenderId: '223244759279',
    projectId: 'gemdoc-22afc',
    storageBucket: 'gemdoc-22afc.firebasestorage.app',
    iosBundleId: 'com.example.gemdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtvZRZCODoT05Woxs7Zp8PrUvKXDYbeZQ',
    appId: '1:223244759279:web:32bf3e402052516e69eb1a',
    messagingSenderId: '223244759279',
    projectId: 'gemdoc-22afc',
    authDomain: 'gemdoc-22afc.firebaseapp.com',
    storageBucket: 'gemdoc-22afc.firebasestorage.app',
    measurementId: 'G-1PWQY37W1K',
  );
}
